# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rspec", "~> 3.0"
# gem "rake", "~> 10.0"
# gem "aws-sdk-ec2", "~> 1"
# gem "aws_config"